(()=>{"use strict";
const $=s=>document.querySelector(s),esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const sources=[
{name:"Armenian Wikipedia",url:q=>"https://hy.wikipedia.org/w/api.php?action=query&generator=search&gsrsearch="+encodeURIComponent(q)+"&gsrlimit=8&prop=extracts|pageimages&exintro=1&explaintext=1&piprop=thumbnail&pithumbsize=640&format=json&origin=*",parse:j=>Object.values(j.query?.pages||{}).map(p=>({title:p.title,desc:(p.extract||"").slice(0,700),url:"https://hy.wikipedia.org/wiki/"+encodeURIComponent(p.title.replaceAll(" ","_")),image:p.thumbnail?.source,source:"Armenian Wikipedia",kind:"article"}))},
{name:"English Wikipedia",url:q=>"https://en.wikipedia.org/w/api.php?action=query&generator=search&gsrsearch="+encodeURIComponent(q)+"&gsrlimit=8&prop=extracts|pageimages&exintro=1&explaintext=1&piprop=thumbnail&pithumbsize=640&format=json&origin=*",parse:j=>Object.values(j.query?.pages||{}).map(p=>({title:p.title,desc:(p.extract||"").slice(0,700),url:"https://en.wikipedia.org/wiki/"+encodeURIComponent(p.title.replaceAll(" ","_")),image:p.thumbnail?.source,source:"English Wikipedia",kind:"article"}))},
{name:"Wikimedia Commons",url:q=>"https://commons.wikimedia.org/w/api.php?action=query&generator=search&gsrsearch="+encodeURIComponent(q)+"&gsrnamespace=6&gsrlimit=12&prop=imageinfo&iiprop=url|extmetadata&iiurlwidth=900&format=json&origin=*",parse:j=>Object.values(j.query?.pages||{}).map(p=>({title:p.title.replace(/^File:/,""),desc:(p.imageinfo?.[0]?.extmetadata?.ImageDescription?.value||"").replace(/<[^>]*>/g," ").slice(0,500),url:"https://commons.wikimedia.org/wiki/"+encodeURIComponent(p.title.replaceAll(" ","_")),image:p.imageinfo?.[0]?.thumburl||p.imageinfo?.[0]?.url,source:"Wikimedia Commons",kind:"media"}))},
{name:"Internet Archive",url:q=>"https://archive.org/advancedsearch.php?q="+encodeURIComponent(q)+"&fl[]=identifier&fl[]=title&fl[]=description&fl[]=date&fl[]=mediatype&rows=8&page=1&output=json",parse:j=>(j.response?.docs||[]).map(p=>({title:p.title||p.identifier,desc:String(p.description||"").replace(/<[^>]*>/g," ").slice(0,600),url:"https://archive.org/details/"+p.identifier,source:"Internet Archive",meta:[p.mediatype,p.date].filter(Boolean).join(" · "),kind:p.mediatype==="movies"?"video":"archive"}))},
{name:"OpenAlex",url:q=>"https://api.openalex.org/works?search="+encodeURIComponent(q)+"&per-page=6&select=title,publication_year,doi,open_access,primary_location",parse:j=>(j.results||[]).map(p=>({title:p.title,desc:["Research work",p.publication_year,p.open_access?.is_oa?"Open Access":""].filter(Boolean).join(" · "),url:p.doi?"https://doi.org/"+p.doi:p.primary_location?.landing_page_url||"https://openalex.org/",source:"OpenAlex",kind:"research"}))},
{name:"Crossref",url:q=>"https://api.crossref.org/works?query="+encodeURIComponent(q)+"&rows=6&select=title,author,published,URL,DOI",parse:j=>(j.message?.items||[]).map(p=>({title:p.title?.[0]||"Untitled",desc:["Research / publication record",p.published?.["date-parts"]?.[0]?.join("-")].filter(Boolean).join(" · "),url:p.URL||"https://search.crossref.org/",source:"Crossref",kind:"research"}))}
];
const params=new URLSearchParams(location.search),q=params.get("q")||"",chosen=params.get("title")||"";
function norm(s){return String(s||"").toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^\p{L}\p{N}]+/gu," ").trim()}
function similarity(a,b){const x=new Set(norm(a).split(" ").filter(w=>w.length>2)),y=new Set(norm(b).split(" ").filter(w=>w.length>2));if(!x.size||!y.size)return norm(a)===norm(b);let n=0;for(const w of x)if(y.has(w))n++;return n/Math.min(x.size,y.size)}
function group(items){const groups=[];for(const x of items){let g=groups.find(z=>similarity(z.title,x.title)>=.72);if(!g){g={title:x.title,items:[],image:x.image||null};groups.push(g)}g.items.push(x);if(!g.image&&x.image)g.image=x.image}return groups}
function sourceLink(x){return '<a class="detail-source" href="'+esc(x.url)+'" target="_blank" rel="noopener"><span>'+esc(x.source)+'</span><strong>'+esc(x.title||"Original source")+' ↗</strong>'+(x.desc?'<small>'+esc(x.desc.slice(0,420))+'</small>':"")+'</a>'}
function card(g){const n=g.items.length;return '<article class="universal-result">'+(g.image?'<a href="result.html?q='+encodeURIComponent(q)+'&title='+encodeURIComponent(g.title)+'"><img loading="lazy" src="'+esc(g.image)+'" alt=""></a>':'')+'<div class="universal-result-body"><span class="universal-source">'+n+' similar source</span><h3><a href="result.html?q='+encodeURIComponent(q)+'&title='+encodeURIComponent(g.title)+'">'+esc(g.title)+'</a></h3><p>'+esc(g.items.find(x=>x.desc)?.desc||"Open the combined record and original sources.")+'</p><a class="universal-open" href="result.html?q='+encodeURIComponent(q)+'&title='+encodeURIComponent(g.title)+'">Open combined page ↗</a></div></article>'}
async function fetchAll(query){return Promise.all(sources.map(async s=>{try{const r=await fetch(s.url(query));if(!r.ok)throw Error();return s.parse(await r.json())}catch(_){return []}}))}
async function initSearch(){const form=$("#universal-search-form"),input=$("#universal-search-input"),root=$("#universal-search-results");if(!form||!input||!root)return;input.value=q;form.addEventListener("submit",e=>{e.preventDefault();const v=input.value.trim();if(v)location.href="search.html?q="+encodeURIComponent(v)});if(!q)return;root.innerHTML='<div class="search-progress"><span class="loading-orbit"></span><div><strong>Searching and combining…</strong><p>Querying open databases in parallel.</p></div></div>';const all=(await fetchAll(q)).flat(),groups=group(all);root.innerHTML='<div class="search-summary"><div><span class="eyebrow">OPEN KNOWLEDGE SEARCH</span><h2>'+groups.length+' topic groups՝ '+esc(q)+'</h2><p>Results with similar titles are grouped. Each group opens as a separate page with its sources.</p></div><div class="search-source-list">'+sources.map(s=>'<span>'+esc(s.name)+'</span>').join("")+'</div></div>'+(groups.length?'<div class="universal-results-grid">'+groups.map(card).join("")+'</div>':'<div class="empty-state">No results found. Try another query.</div>')}
async function initDetail(){const root=$("#detail-content");if(!root||!q||!chosen)return;root.innerHTML='<div class="search-progress"><span class="loading-orbit"></span><div><strong>Building topic page…</strong><p>Collecting related records and original sources.</p></div></div>';const all=(await fetchAll(q)).flat(),groups=group(all),g=groups.find(x=>similarity(x.title,chosen)>=.72)||{title:chosen,items:all.filter(x=>similarity(x.title,chosen)>=.35),image:null};const items=g.items||[];const excerpts=[...new Set(items.map(x=>x.desc).filter(Boolean))].slice(0,5);const media=items.filter(x=>x.image||x.kind==="video");root.innerHTML='<section class="detail-hero"><div class="eyebrow">HISTORY · COMBINED RECORD</div><h1>'+esc(g.title)+'</h1><p>This page combines related records found during the search. Descriptions come from their respective sources; they are automatically combined and are not independent historical conclusions.</p><div class="detail-stats"><span><b>'+items.length+'</b> records</span><span><b>'+new Set(items.map(x=>x.source)).size+'</b> sources</span><span><b>'+media.length+'</b> media</span></div></section><div class="detail-layout"><main><section class="detail-section"><h2>Combined material</h2>'+(excerpts.length?excerpts.map((d,i)=>'<article class="excerpt"><span>Source description '+(i+1)+'</span><p>'+esc(d)+'</p></article>').join(""):'<p>No descriptive text was returned for this topic.</p>')+'</section>'+(media.length?'<section class="detail-section"><h2>Images and videos</h2><div class="detail-media">'+media.map(x=>'<a href="'+esc(x.url)+'" target="_blank" rel="noopener">'+(x.image?'<img loading="lazy" src="'+esc(x.image)+'" alt="">':"▶")+'<span>'+esc(x.title)+'</span></a>').join("")+'</div></section>':'')+'<section class="detail-section"><h2>Բոլոր սկզբնsourcesները</h2><div class="detail-sources">'+items.map(sourceLink).join("")+'</div></section></main><aside class="detail-aside"><strong>About the sources</strong><p>Each link opens the original record. Materials may be in different languages and may differ from one another.</p><a href="search.html?q='+encodeURIComponent(q)+'">← Back to results</a></aside></div>'}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",()=>{initSearch();initDetail()});else{initSearch();initDetail()}
})();